# Generated by Django 3.2.11 on 2022-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('Services', models.CharField(choices=[('Electricity bill', 'Electricity bill'), ('Water bill', 'Water Bill'), ('Refuse Fee', 'Refuse Fee')], max_length=100)),
                ('totalAmount', models.CharField(max_length=100)),
            ],
        ),
    ]
