# Generated by Django 3.2.11 on 2022-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='invoice_no',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='Services',
            field=models.CharField(max_length=100),
        ),
    ]
